os: linux
dist: bionic

services: docker

language: shell

branches:
  only:
    - main
    - master
    - develop

before_install:
  - env | sort

install:
  # Execute CI build hooks
  - ./hooks/run build

before_script:
  # Display docker images
  - docker images

script:
  # Execute CI test hooks
  - ./hooks/run test

notifications:
  email: false

matrix:
  allow_failures:
    - env: VARIANT=debian

env: # Environments
  - VARIANT=alpine
