os: linux
dist: trusty

services: docker

language: shell

branches:
  only:
    - master

before_install:
  - env | sort
  - export home=$(pwd)
  - export travis_dir="${home}"

install:
  - echo "Changing to travis test directory ($travis_dir)"
  - cd "$travis_dir"
  # Test container build
  - travis_retry docker-compose build

before_script:
  - docker images

script:
  - echo "Changing to travis test directory ($travis_dir)"
  - cd "$travis_dir"
  # Test container run
  - travis_retry docker-compose up -d && sleep 20
  - docker-compose ps
  - docker-compose logs
  - docker-compose ps | grep "Up" || exit 1
  - echo 'Wait a bit' && sleep 60
  - docker-compose ps
  - docker-compose logs
  - docker-compose ps | grep "Up"
  # Test container restart
  - docker-compose down
  - travis_retry docker-compose up -d && sleep 20
  - docker-compose ps
  - docker-compose logs
  - docker-compose ps | grep "Up"
  - echo 'Wait a bit again' && sleep 60
  - docker-compose logs
  - docker-compose ps | grep "Up"

notifications:
  email: false

matrix:
  allow_failures:
    - env: VARIANT=debian

env: # Environments
  - VARIANT=alpine
